export type Lang = "en" | "de";

export const LANGS: { code: Lang; label: string; htmlLang: string }[] = [
  { code: "en", label: "EN", htmlLang: "en" },
  { code: "de", label: "DE", htmlLang: "de" },
];

const en = {
  meta: {
    title: "Lumera Clinic — Network of medical centers in Hamburg",
    description:
      "11 clinics in Hamburg, 70+ doctors with international experience, appointments in English and German. Book online in a minute.",
  },
  nav: {
    services: "Services",
    checkup: "Check-up",
    about: "About us",
    doctors: "Doctors",
    locations: "Locations",
    faq: "FAQ",
  },
  header: {
    hours: "Daily 08:00–21:00",
    book: "Book appointment",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    language: "Language",
    call: "Call us",
  },
  hero: {
    badge: "Network of medical centers in Hamburg",
    titleA: "Doctors who",
    titleB: "understand",
    titleC: "you",
    subtitle:
      "Primary care, dentistry, women's health, pediatrics and diagnostics under one roof — with specialists who speak your language and take time to listen.",
    ctaPrimary: "Book appointment",
    ctaSecondary: "Catalog of services",
    stats: [
      { value: "11", label: "clinics in Hamburg" },
      { value: "2", label: "languages (EN · DE)" },
      { value: "7/7", label: "working schedule" },
    ],
    pillValue: ">70",
    pillText: "Doctors with international experience in 25 fields",
    rating: "Google rating",
    reviews: "2 400+ reviews",
    promiseTitle: "We speak your language",
    promiseText: "English · German",
    chiefRole: "Chief physician",
    chiefName: "Dr. Lena Hartmann",
    chiefMeta: "Therapist · 18 years of practice",
    available: "Available today",
  },
  services: {
    eyebrow: "Our directions",
    title: "Six directions. One standard of care.",
    subtitle:
      "Hover over a direction to explore it — every service is delivered by certified specialists with modern equipment.",
    book: "Book",
    from: "from",
    items: [
      {
        title: "Therapy",
        desc: "Your first stop for any health concern: examination, diagnosis, treatment plan and referrals to narrow specialists.",
        tags: ["Consultation", "Home visits", "Sick leave", "Vaccination"],
        price: "from €80",
      },
      {
        title: "Dentistry",
        desc: "Painless treatment, hygiene, orthodontics and implants. Digital 3D diagnostics and gentle anesthesia.",
        tags: ["Hygiene", "Implants", "Braces", "Whitening"],
        price: "from €70",
      },
      {
        title: "Women's health",
        desc: "Gynecology, pregnancy care, cytology and hormonal health with empathy and absolute confidentiality.",
        tags: ["Gynecology", "Pregnancy", "Cytology", "Hormones"],
        price: "from €90",
      },
      {
        title: "Pediatrics",
        desc: "Caring pediatricians for newborns to teenagers: check-ups, vaccinations and a child-friendly atmosphere.",
        tags: ["Newborns", "Vaccines", "Allergy", "Development"],
        price: "from €75",
      },
      {
        title: "Diagnostics",
        desc: "Ultrasound, ECG, X-ray and laboratory tests — fast results and detailed explanation from a doctor.",
        tags: ["Ultrasound", "ECG", "X-ray", "Laboratory"],
        price: "from €40",
      },
      {
        title: "Psychiatry",
        desc: "Confidential support in your native language: anxiety, depression, burnout and sleep disorders.",
        tags: ["Anxiety", "Depression", "Sleep", "Therapy"],
        price: "from €120",
      },
    ],
    express: {
      badge: "Express analyses",
      title: "Lab results in as little as 2 hours",
      desc: "Walk in without an appointment, give a sample and receive your results by SMS or e-mail the same day.",
      tags: ["Blood test", "Vitamins", "Enzymes", "Specific proteins", "Hormones"],
      highlights: ["No appointment needed", "Results same day", "Doctor's comment included"],
      cta: "Book a blood draw",
      resultTitle: "Your results are ready",
      resultRows: ["Hemoglobin", "Vitamin D", "TSH"],
      resultNorm: "Normal",
      resultTime: "Ready in 1 h 48 min",
    },
  },
  checkup: {
    eyebrow: "Check-up programs",
    title: "Know your health. Prevent, don't treat.",
    subtitle:
      "Ready-made programs designed by our doctors: save up to 30% compared with ordering each test separately.",
    from: "from",
    featured: "Most popular",
    discount: "-15% discount",
    book: "Book appointment",
    note: "Prices are indicative. Final cost is confirmed at registration.",
    plans: [
      {
        name: "Basic",
        desc: "Annual preventive check for healthy adults.",
        features: [
          "Complete blood count",
          "Glucose & cholesterol",
          "Liver tests (ALT, AST)",
          "Kidney function (creatinine)",
          "General urine analysis",
          "Therapist consultation",
        ],
      },
      {
        name: "Extended 40+",
        desc: "Deeper screening of the heart, hormones and digestion.",
        features: [
          "Everything in Basic",
          "Hormone panel (TSH, T3, T4)",
          "Cardiologist + ECG",
          "Abdominal ultrasound",
          "Vitamin D & B12",
          "Tumor markers",
          "Gastroenterologist consultation",
        ],
      },
      {
        name: "Women's health",
        desc: "Complete care program for women of any age.",
        features: [
          "Gynecologist consultation",
          "Pelvic ultrasound",
          "Cytology (PAP smear)",
          "Hormones (FSH, LH, estradiol)",
          "Breast ultrasound",
          "Iron, ferritin, vitamins",
        ],
      },
    ],
  },
  about: {
    eyebrow: "Why Lumera",
    title: "A clinic built around the person",
    subtitle:
      "We combine European standards of medicine with the warmth of an attentive team — so that every visit feels clear, comfortable and safe.",
    values: [
      {
        title: "International diplomas",
        desc: "Doctors trained and certified in Germany, with ongoing international education and training.",
      },
      {
        title: "Multilingual support",
        desc: "Appointments, documents and follow-ups in English and German.",
      },
      {
        title: "Modern equipment",
        desc: "Digital diagnostics, in-house laboratory and expert-class ultrasound in every flagship clinic.",
      },
      {
        title: "Individual approach",
        desc: "Unhurried visits, personal treatment plans and a coordinator who stays with you to the end.",
      },
    ],
    stats: [
      { value: 11, suffix: "", label: "branches in Hamburg" },
      { value: 100, suffix: "K+", label: "patients per year" },
      { value: 50, suffix: "+", label: "types of diagnostics" },
      { value: 70, suffix: "+", label: "specialists" },
    ],
  },
  doctors: {
    eyebrow: "Our team",
    title: "Meet the doctors you can trust",
    subtitle: "Experienced specialists with international practice, rated by thousands of patients.",
    book: "Book",
    specs: [
      "Therapist",
      "Gastroenterologist",
      "Gynecologist",
      "Dentist",
      "Pediatrician",
      "Cardiologist",
    ],
    experience: "yrs experience",
  },
  locations: {
    eyebrow: "Locations",
    title: "11 clinics across Hamburg",
    subtitle: "Choose the most convenient branch — every one is a short walk from public transport.",
    open: "Open today",
    hours: "Mon–Sun 08:00–21:00",
    directions: "Get directions",
    call: "Call",
    book: "Book at this branch",
    more: "+ 5 more branches — see the full list at registration",
    offers: "Available here",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions we hear most",
    subtitle: "Can't find your answer? Call us or book an appointment — we're happy to help.",
  },
  booking: {
    title: "Book an appointment",
    subtitle: "Leave your details and we'll confirm the visit within 15 minutes.",
    name: "Full name",
    namePh: "Jane Doe",
    phone: "Phone number",
    phonePh: "+49 123 456789",
    spec: "Specialization",
    specPh: "Select specialization",
    doctor: "Doctor",
    doctorAny: "Any available doctor",
    date: "Preferred date",
    time: "Preferred time",
    submit: "Confirm booking",
    sending: "Sending…",
    privacy: "By submitting you agree to the processing of personal data.",
    close: "Close",
    errName: "Please enter your name",
    errPhone: "Please enter a valid phone number",
    errSpec: "Please choose a specialization",
    errDate: "Please choose a date",
    errTime: "Please choose a time",
    successTitle: "Request received!",
    successText: "Thank you, {name}. Our coordinator will call you shortly to confirm your visit.",
    summary: "Your request",
    another: "Book another visit",
  },
  footer: {
    about:
      "A network of modern medical centers in Hamburg. Doctors who speak your language and care about the result.",
    links: "Quick links",
    contacts: "Contacts",
    hours: "Working hours",
    hoursRows: ["Mon–Fri: 08:00–21:00", "Saturday: 09:00–20:00", "Sunday: 09:00–18:00"],
    addresses: "Addresses",
    legal:
      "Information on this website is for reference only and does not replace consultation with a qualified doctor. Contraindications exist — consult a specialist.",
    rights: "All rights reserved.",
    privacy: "Privacy policy",
    terms: "Terms of service",
    cookies: "Cookies",
    email: "hello@lumera-clinic.example",
    emergency: "Emergency: 112",
  },
};

export type Dict = typeof en;

const de: Dict = {
  meta: {
    title: "Lumera Clinic — Netzwerk medizinischer Zentren in Hamburg",
    description:
      "11 Kliniken in Hamburg, über 70 Ärztinnen und Ärzte mit internationaler Erfahrung, Sprechstunden auf Englisch und Deutsch. Online Termin buchen in einer Minute.",
  },
  nav: {
    services: "Leistungen",
    checkup: "Check-up",
    about: "Über uns",
    doctors: "Ärzte",
    locations: "Standorte",
    faq: "FAQ",
  },
  header: {
    hours: "Täglich 08:00–21:00",
    book: "Termin buchen",
    openMenu: "Menü öffnen",
    closeMenu: "Menü schließen",
    language: "Sprache",
    call: "Anrufen",
  },
  hero: {
    badge: "Netzwerk medizinischer Zentren in Hamburg",
    titleA: "Ärzte, die Sie",
    titleB: "verstehen",
    titleC: "",
    subtitle:
      "Allgemeinmedizin, Zahnmedizin, Frauengesundheit, Pädiatrie und Diagnostik unter einem Dach — mit Fachleuten, die Ihre Sprache sprechen und sich Zeit für Sie nehmen.",
    ctaPrimary: "Termin buchen",
    ctaSecondary: "Leistungskatalog",
    stats: [
      { value: "11", label: "Kliniken in Hamburg" },
      { value: "2", label: "Sprachen (EN · DE)" },
      { value: "7/7", label: "geöffnet" },
    ],
    pillValue: ">70",
    pillText: "Ärzte mit internationaler Erfahrung in 25 Fachbereichen",
    rating: "Google-Bewertung",
    reviews: "2 400+ Bewertungen",
    promiseTitle: "Wir sprechen Ihre Sprache",
    promiseText: "Englisch · Deutsch",
    chiefRole: "Chefärztin",
    chiefName: "Dr. Lena Hartmann",
    chiefMeta: "Internistin · 18 Jahre Praxis",
    available: "Heute verfügbar",
  },
  services: {
    eyebrow: "Unsere Bereiche",
    title: "Sechs Bereiche. Ein Qualitätsanspruch.",
    subtitle:
      "Fahren Sie mit der Maus über einen Bereich, um mehr zu erfahren — alle Leistungen werden von zertifizierten Fachleuten mit moderner Ausstattung erbracht.",
    book: "Buchen",
    from: "ab",
    items: [
      {
        title: "Allgemeinmedizin",
        desc: "Ihre erste Anlaufstelle bei jedem Gesundheitsanliegen: Untersuchung, Diagnose, Behandlungsplan und Überweisung zu Fachärzten.",
        tags: ["Beratung", "Hausbesuche", "Krankschreibung", "Impfungen"],
        price: "ab 80 €",
      },
      {
        title: "Zahnmedizin",
        desc: "Schmerzfreie Behandlung, Prophylaxe, Kieferorthopädie und Implantate. Digitale 3D-Diagnostik und sanfte Betäubung.",
        tags: ["Prophylaxe", "Implantate", "Zahnspangen", "Bleaching"],
        price: "ab 70 €",
      },
      {
        title: "Frauengesundheit",
        desc: "Gynäkologie, Schwangerschaftsbetreuung, Zytologie und hormonelle Gesundheit — einfühlsam und streng vertraulich.",
        tags: ["Gynäkologie", "Schwangerschaft", "Zytologie", "Hormone"],
        price: "ab 90 €",
      },
      {
        title: "Pädiatrie",
        desc: "Fürsorgliche Kinderärzte für Neugeborene bis Jugendliche: Vorsorge, Impfungen und eine kindgerechte Atmosphäre.",
        tags: ["Neugeborene", "Impfungen", "Allergien", "Entwicklung"],
        price: "ab 75 €",
      },
      {
        title: "Diagnostik",
        desc: "Ultraschall, EKG, Röntgen und Labortests — schnelle Ergebnisse und ausführliche Erklärung durch den Arzt.",
        tags: ["Ultraschall", "EKG", "Röntgen", "Labor"],
        price: "ab 40 €",
      },
      {
        title: "Psychiatrie",
        desc: "Vertrauliche Unterstützung in Ihrer Muttersprache: Angst, Depression, Burnout und Schlafstörungen.",
        tags: ["Angst", "Depression", "Schlaf", "Therapie"],
        price: "ab 120 €",
      },
    ],
    express: {
      badge: "Express-Analysen",
      title: "Laborergebnisse in nur 2 Stunden",
      desc: "Kommen Sie ohne Termin, geben Sie eine Probe ab und erhalten Sie Ihre Ergebnisse noch am selben Tag per SMS oder E-Mail.",
      tags: ["Blutbild", "Vitamine", "Enzyme", "Spezifische Proteine", "Hormone"],
      highlights: ["Ohne Termin", "Ergebnis am selben Tag", "Ärztlicher Kommentar inklusive"],
      cta: "Blutabnahme buchen",
      resultTitle: "Ihre Ergebnisse sind fertig",
      resultRows: ["Hämoglobin", "Vitamin D", "TSH"],
      resultNorm: "Normal",
      resultTime: "Fertig in 1 Std. 48 Min.",
    },
  },
  checkup: {
    eyebrow: "Check-up-Programme",
    title: "Kennen Sie Ihre Gesundheit. Vorbeugen statt heilen.",
    subtitle:
      "Fertige Programme von unseren Ärzten: bis zu 30 % günstiger als einzelne Untersuchungen.",
    from: "ab",
    featured: "Am beliebtesten",
    discount: "-15 % Rabatt",
    book: "Termin buchen",
    note: "Preise sind Richtwerte. Der endgültige Preis wird bei der Anmeldung bestätigt.",
    plans: [
      {
        name: "Basis",
        desc: "Jährliche Vorsorge für gesunde Erwachsene.",
        features: [
          "Großes Blutbild",
          "Glukose & Cholesterin",
          "Leberwerte (ALT, AST)",
          "Nierenfunktion (Kreatinin)",
          "Urinstatus",
          "Beratung beim Internisten",
        ],
      },
      {
        name: "Erweitert 40+",
        desc: "Vertiefte Untersuchung von Herz, Hormonen und Verdauung.",
        features: [
          "Alles aus Basis",
          "Hormonpanel (TSH, T3, T4)",
          "Kardiologe + EKG",
          "Ultraschall des Bauchraums",
          "Vitamin D & B12",
          "Tumormarker",
          "Beratung beim Gastroenterologen",
        ],
      },
      {
        name: "Frauengesundheit",
        desc: "Umfassendes Programm für Frauen jeden Alters.",
        features: [
          "Beratung beim Gynäkologen",
          "Ultraschall des Beckens",
          "Zytologie (PAP-Abstrich)",
          "Hormone (FSH, LH, Östradiol)",
          "Brustultraschall",
          "Eisen, Ferritin, Vitamine",
        ],
      },
    ],
  },
  about: {
    eyebrow: "Warum Lumera",
    title: "Eine Klinik, die den Menschen in den Mittelpunkt stellt",
    subtitle:
      "Wir verbinden europäische Medizinstandards mit der Wärme eines aufmerksamen Teams — damit jeder Besuch verständlich, angenehm und sicher ist.",
    values: [
      {
        title: "Internationale Abschlüsse",
        desc: "Ärzte mit deutscher Ausbildung und Zertifizierung, die sich international ständig weiterbilden.",
      },
      {
        title: "Mehrsprachige Betreuung",
        desc: "Sprechstunden, Dokumente und Nachsorge auf Englisch und Deutsch.",
      },
      {
        title: "Moderne Ausstattung",
        desc: "Digitale Diagnostik, eigenes Labor und Expertenultraschall in jeder Flaggschiff-Klinik.",
      },
      {
        title: "Individuelle Betreuung",
        desc: "Ohne Zeitdruck, mit persönlichem Behandlungsplan und einem Koordinator, der Sie bis zum Ergebnis begleitet.",
      },
    ],
    stats: [
      { value: 11, suffix: "", label: "Standorte in Hamburg" },
      { value: 100, suffix: "K+", label: "Patienten pro Jahr" },
      { value: 50, suffix: "+", label: "Diagnostikarten" },
      { value: 70, suffix: "+", label: "Fachärzte" },
    ],
  },
  doctors: {
    eyebrow: "Unser Team",
    title: "Lernen Sie Ärzte kennen, denen Sie vertrauen können",
    subtitle: "Erfahrene Fachärzte mit internationaler Praxis, bewertet von tausenden Patienten.",
    book: "Buchen",
    specs: [
      "Internistin",
      "Gastroenterologe",
      "Gynäkologin",
      "Zahnarzt",
      "Kinderärztin",
      "Kardiologe",
    ],
    experience: "Jahre Erfahrung",
  },
  locations: {
    eyebrow: "Standorte",
    title: "11 Kliniken in ganz Hamburg",
    subtitle: "Wählen Sie den passenden Standort — jeder liegt nur wenige Minuten von öffentlichen Verkehrsmitteln entfernt.",
    open: "Heute geöffnet",
    hours: "Mo–So 08:00–21:00",
    directions: "Route planen",
    call: "Anrufen",
    book: "An diesem Standort buchen",
    more: "+ 5 weitere Standorte — vollständige Liste bei der Anmeldung",
    offers: "Hier verfügbar",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Häufige Fragen",
    subtitle: "Ihre Frage ist nicht dabei? Rufen Sie uns an oder buchen Sie einen Termin — wir helfen gerne.",
  },
  booking: {
    title: "Termin buchen",
    subtitle: "Hinterlassen Sie Ihre Daten — wir bestätigen den Termin innerhalb von 15 Minuten.",
    name: "Vor- und Nachname",
    namePh: "Max Mustermann",
    phone: "Telefonnummer",
    phonePh: "+49 123 456789",
    spec: "Fachrichtung",
    specPh: "Fachrichtung wählen",
    doctor: "Arzt",
    doctorAny: "Beliebiger verfügbarer Arzt",
    date: "Wunschdatum",
    time: "Wunschzeit",
    submit: "Buchung bestätigen",
    sending: "Wird gesendet…",
    privacy: "Mit dem Absenden stimmen Sie der Verarbeitung Ihrer personenbezogenen Daten zu.",
    close: "Schließen",
    errName: "Bitte geben Sie Ihren Namen ein",
    errPhone: "Bitte geben Sie eine gültige Telefonnummer ein",
    errSpec: "Bitte wählen Sie eine Fachrichtung",
    errDate: "Bitte wählen Sie ein Datum",
    errTime: "Bitte wählen Sie eine Uhrzeit",
    successTitle: "Anfrage erhalten!",
    successText: "Vielen Dank, {name}. Unser Koordinator ruft Sie in Kürze an, um den Termin zu bestätigen.",
    summary: "Ihre Anfrage",
    another: "Weiteren Termin buchen",
  },
  footer: {
    about:
      "Ein Netzwerk moderner medizinischer Zentren in Hamburg. Ärzte, die Ihre Sprache sprechen und für das Ergebnis einstehen.",
    links: "Schnellzugriff",
    contacts: "Kontakt",
    hours: "Öffnungszeiten",
    hoursRows: ["Mo–Fr: 08:00–21:00", "Samstag: 09:00–20:00", "Sonntag: 09:00–18:00"],
    addresses: "Adressen",
    legal:
      "Die Informationen auf dieser Website dienen nur der Orientierung und ersetzen keine Beratung durch einen qualifizierten Arzt. Es bestehen Gegenanzeigen — bitte konsultieren Sie einen Facharzt.",
    rights: "Alle Rechte vorbehalten.",
    privacy: "Datenschutzerklärung",
    terms: "Nutzungsbedingungen",
    cookies: "Cookies",
    email: "hello@lumera-clinic.example",
    emergency: "Notruf: 112",
  },
};

export const dictionaries: Record<Lang, Dict> = { en, de };

/**
 * Neutral wording used for real tenant sites. The default texts above describe the Lumera sample clinic
 * (number of branches, opening hours, emergency line, ...), so they must never leak into a customer's site.
 */
export const tenantTexts = {
  en: {
    ctaSecondary: "Our services",
    services: { eyebrow: "Our services", title: "What we offer", subtitle: "" },
    checkup: { eyebrow: "Check-up programs", title: "Prevention that fits you", subtitle: "", discount: "" },
    about: { eyebrow: "About us", title: "", subtitle: "" },
    doctors: { eyebrow: "Our team", title: "Meet our team", subtitle: "" },
    locations: { eyebrow: "Locations", title: "Find us", subtitle: "", more: "", open: "" },
  },
  de: {
    ctaSecondary: "Unsere Leistungen",
    services: { eyebrow: "Unsere Leistungen", title: "Was wir anbieten", subtitle: "" },
    checkup: { eyebrow: "Check-up-Programme", title: "Vorsorge, die zu Ihnen passt", subtitle: "", discount: "" },
    about: { eyebrow: "Über uns", title: "", subtitle: "" },
    doctors: { eyebrow: "Unser Team", title: "Lernen Sie unser Team kennen", subtitle: "" },
    locations: { eyebrow: "Standorte", title: "So finden Sie uns", subtitle: "", more: "", open: "" },
  },
} as const;
export const DEFAULT_LANG: Lang = "en";
